# Generated by Django 4.1.3 on 2022-11-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options_alter_service_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='url1',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='service',
            name='url2',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='service',
            name='url3',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
    ]
