# Generated by Django 4.1.3 on 2022-11-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='img/products-02.jpg', null=True, upload_to='blog', verbose_name='Imagen'),
        ),
    ]
