# Generated by Django 4.1.3 on 2022-11-17 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['name'], 'verbose_name': 'Enlace', 'verbose_name_plural': 'Enlaces'},
        ),
    ]
